kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-vpc-block-csi-configmap-and-secret-reader-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: ibm-vpc-block-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: openshift-csi-provisioner-configmap-and-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
