apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
  name: vpc-block-driver-registrar-role
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - delete
